server:
  port: 8081

info:
  app:
    name: CarsdawRestApi
    description: Entry to app
    version: 0.0.1-SNAPSHOT

services:
  carsdawRepairsService: https://carsdaw-repairs-service.herokuapp.com/


